name: Rustdoc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libgtk-4-dev libgtk-3-dev libatk1.0-dev --yes
    - uses: actions/checkout@v4
    - name: Doc
      run: cargo doc --verbose
    - name: Doctest
      run: cargo test --doc --verbose
