name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - name: Install dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install libgtk-4-dev libgtk-3-dev libatk1.0-dev --yes
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      if: ${{ matrix.os != 'ubuntu-latest' }}
      run: cargo test --verbose
